### ISSUE TITLE
Developer name not shown for Sharing app

### ISSUE THREAD

**Issue by Ammar64** [mobilenetworkltd/openapk#2]
I'm the developer of Sharing app and I'm glad that you included my app in your repo but my name is not shown please type Ammar64 under the Developer label
and if possible link it to my github page I'd be grateful
Thanks.
![image](https://github.com/user-attachments/assets/42b23cc6-4dea-4ed9-a532-9f14a5763f1b)

**Comment by mnalis** [comment]
Is that app this one https://www.openapk.net/sharing/com.ammar.filescenter/ @Ammar64?

It is hard to know why it is missing data until we get to see the OpenAPK source (see prematurely closed https://github.com/mobilenetworkltd/openapk/issues/1) , but you can take a look at repos which do have Developer correctly specified, and try to see what they have in common regarding author name and that your repo doesn't have, e.g.:

- https://www.openapk.net/streetcomplete/de.westnordost.streetcomplete/
- https://www.openapk.net/obtainium/dev.imranr.obtainium/


Of course that is assuming that info is fetched automatically. It might also be the case that someone manually types Developer names in their database from which the OpenAPK is generated - we just don't know (as noted above, OpenAPK would have to become _open source_ itself before external people could verify what is going on). 


One different thing I've noticed is they get direct download links to GitHub release page (e.g. `https://github.com/streetcomplete/StreetComplete/releases/download/v58.2/StreetComplete-v58.2.apk` or `https://github.com/ImranR98/Obtainium/releases/download/v1.1.15/app-fdroid-release.apk`), while your package is (for some reason) linked via some redirector at `https://www.openapk.net/serve/?token=BcEBCoAgDADAF7XhtIQ-M0RnSdlk-n-6C84T873WmCdi3YppK6B2oclQzNoh9Z4MantlZvmWGDtI42F2kShEf9D-Aw`

**Comment by mnalis** [comment]
Also on F-droid repo working StreetComplete has author name specified at  https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.westnordost.streetcomplete.yml#L8: 

> AuthorName: Tobias Zwick
AuthorEmail: osm@westnordost.de

While your package seems to be missing those fields:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.ammar.filescenter.yml

**Comment by Ammar64** [comment]
It is shown now but don't forget to remove the old package named `com.ammar.filescenter` since it's replaced with `com.ammar.sharing`.
See this [issue](https://github.com/Ammar64/Sharing/issues/9)

**Comment by mobilenetworkltd** [comment]
@Ammar64 the old package name listing has been removed, and now we list and follow your GitHub repo with the new package name at https://www.openapk.net/sharing/com.ammar.sharing/

All releases will be automatically listed at OpenAPK.
