### ISSUE TITLE
Sharing update icon

### ISSUE THREAD

**Issue by Ammar64** [mobilenetworkltd/openapk#6]
Hi  
Sharing icon changed since v1.5.3  as well as the license
| License | Icon |
| - | - |
| AGPLv3-only | <img src="https://github.com/Ammar64/Sharing/raw/master/fastlane/metadata/android/en-US/images/icon.png" height="100"/> |

**Comment by Ammar64** [comment]
here https://www.openapk.net/sharing/com.ammar.sharing/

**Comment by mobilenetworkltd** [comment]
Updated, thanks !
